logging:
  file:
    name: ./logs/hello-docker.log
  level:
    root: INFO

environment:
  path: "file:./environment/int/"

spring:
  config:
    import:
      - ${environment.path}/another_custom.properties
      - ${environment.path}/custom.properties


server:
  servlet:
    context-path: /hello-docker-app